mode: Mainline
branches: {}
ignore:
  sha: []
merge-message-formats: {}
major-version-bump-message: 'breaking\s?(\(\w*\)|):'
minor-version-bump-message: 'feat\s?(\(\w*\)|):'
patch-version-bump-message: '\s?(fix|perf|refactor)(\(\w*\)|):'
no-bump-message: '\s?(docs|chore|test|ci|build)(\(\w*\)|)'