name: DotnetCore
description: 'Build, test, package, or publish a dotnet application, or run a custom dotnet command.'
inputs:
  command:
    required: true
    type: string
  arguments:
    required: true
    type: string
  projects:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: dotnet ${{ inputs.command }}
      shell: bash
      run: |
        filter="${{ inputs.projects }}"
        for file in $filter; do
          if [ "$file" = "$filter" ]
          then
              echo "No match found: $file"
          else
              echo "${{ inputs.command }} $file"
              echo "cmd: dotnet ${{ inputs.command }} $file ${{inputs.arguments}}"
              dotnet ${{ inputs.command }} $file ${{inputs.arguments}}
          fi
        done