name: DotnetCore
description: 'Build, test, package, or publish a dotnet application, or run a custom dotnet command.'
inputs:
  command:
    required: true
    type: string
  arguments:
    required: true
    type: string
  projects:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: dotnet ${{ inputs.command }}
      shell: bash
      run: |
        for file in ${{ inputs.projects }}; do
            echo "${{ inputs.command }} $file"
            echo "cmd: dotnet ${{ inputs.command }} $file ${{inputs.arguments}}"
            dotnet ${{ inputs.command }} $file ${{inputs.arguments}}
        done