name: GitVersionTag
description: 'GitVersionTag action'

runs:
  using: "composite"
  steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: "5.x"
    - name: Determine GitVersion
      id:   gitversion # id to later be referenced
      uses: gittools/actions/gitversion/execute@v0
      with:
          useConfigFile: true
          configFilePath: ${{ github.action_path }}/../../GitVersion.yml
    - uses: mukunku/tag-exists-action@v1.2.0
      id: checkTag
      with: 
        tag: '${{ steps.gitversion.outputs.semVer }}'
    - name: Output tag status
      shell: bash
      run: | 
        echo "Tag exists: ${{ steps.checkTag.outputs.exists }}. Skipping tagging."
    - name: Tag version
      if: ${{ github.ref == 'refs/heads/main' && steps.checkTag.outputs.exists == 'false' }}
      shell: bash
      run: |
        git config user.name "GitHub Action"
        git config user.email "github-action@users.noreply.github.com>"
        git tag -a "${{ steps.gitversion.outputs.semVer }}" -m "Tagged version ${{ steps.gitversion.outputs.semVer }}"
        git push origin "${{ steps.gitversion.outputs.semVer }}"