name: GitVersionTag
description: "GitVersionTag action"

runs:
  using: "composite"
  steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: "5.x"
    - name: Determine GitVersion
      id:   gitversion # id to later be referenced
      uses: gittools/actions/gitversion/execute@v0
      with:
          useConfigFile: true
          configFilePath: ${{ github.action_path }}/../../GitVersion.yml
    - uses: mukunku/tag-exists-action@v1.2.0
      id: checkTag
      with: 
        tag: '${{ steps.gitversion.outputs.semVer }}'
    - name: Output tag status
      shell: bash
      run: | 
        echo "Ref: ${{ github.ref }}"
        echo "Default branch: ${{ github.event.repository.default_branch  }}"
        echo "Tag exists: ${{ steps.checkTag.outputs.exists }}."
    - name: Tag version
      if: ${{ github.ref == github.event.repository.default_branch && steps.checkTag.outputs.exists == 'false' }}
      uses: "evoy-as/.github/.github/actions/git-tag@main"
      with:
        annotation: "Tagged version ${{ steps.gitversion.outputs.semVer }}"
        tag: "${{ steps.gitversion.outputs.semVer }}"
        user-name: "GitHub Action"
        user-email: "github-action@users.noreply.github.com"
