name: GitVersionTag
description: 'GitVersionTag action'

runs:
  using: "composite"
  if: ${{ github.ref == 'ref/heads/main' }}
  steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: "5.x"
    - name: Determine GitVersion
      id:   gitversion # id to later be referenced
      uses: gittools/actions/gitversion/execute@v0
      with:
          useConfigFile: true
          configFilePath: ./.github/GitVersion.yml
   - name: Tag version
        if: ${{ github.ref == 'refs/heads/main' }}
        shell: bash
        run: |
          git config user.name "GitHub Action"
          git config user.email "github-action@users.noreply.github.com>"
          git tag -a "v${{ steps.gitversion.outputs.semVer }}" -m "Tagged version v${{ steps.gitversion.outputs.semVer }}"
          git push origin ${{ steps.gitversion.outputs.semVer }}