#### 
# Requires a file named edge-deployment.json in the repo using the template.
# See sample manifest: DeployEdgeManifest.json
#
####
name: IotEdgeManifestDeploy
description: 'Deploy IoT Edge manifest'
inputs:
  azure_rbac_credentials:
    required: true
    type: string
  sem_ver:
    required: true
    type: string
  image:
    required: true
    type: string
  edge_deployment_fileName:
    required: false
    type: string
    default: edge-deployment.json
  target_condition:
    required: true
    type: string
    default: tags.notset='true'
  priority:
    required: false
    type: string
    default: 3
runs:
  using: "composite"
  steps:
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure_rbac_credentials }}
    - name: 'Set image url in manifest file'
      uses: cschleiden/replace-tokens@v1
      with:
        files: '["edge-deployment.json"]'
      env:
        IMAGE: ${{ inputs.image }}
    - name: Show edge deployment
      shell: bash
      run: |
          cat edge-deployment.json
    - name: 'Deploy edge manifest to IoT Hub'
      shell: bash
      run: |
        branch_name=${{ github.head_ref }}
        echo "Branch: $branch_name"
        build_id="${{ inputs.sem_ver }}"
        deployment_name="ci-${{ github.event.repository.name }}"


        echo "Install azure-iot extension"
        az config set extension.use_dynamic_install=yes_without_prompt
        az extension add --name azure-iot
        
        build_id=$(echo $build_id | sed 's/\./_/g')
        
        if [ "$branch_name" == "refs/heads/main" ]; then
            env="prod"
        else 
            env="dev"
        fi 
        iot_hub_name=$(az iot hub list --query "[?starts_with(name,'iot-$env-evoy-')].name" --output tsv)
        echo "Deploying to IoT Hub: '$iot_hub_name'"
        existingDeployment=$(az iot edge deployment list --hub-name $iot_hub_name --query "reverse(sort_by([?starts_with(id,'$deployment_name')].{id:id, created:createdTimeUtc}, &created))[0].id" --output tsv)
        
        deployment_name="$deployment_name-$build_id"
        echo "Creating deployment: '$deployment_name'"
        az iot edge deployment create -n $iot_hub_name -d "$deployment_name" --content edge-deployment.json --target-condition "${{ inputs.target_condition }}" --layered --priority ${{ inputs.priority }}
        
        if [ ! -z "$existingDeployment" ]
        then
            echo "Deleting previous deployment: '$existingDeployment'"
            az iot edge deployment delete -n $iot_hub_name -d "$existingDeployment"
        fi

    - name: Azure logout
      shell: bash
      run: |
        az logout