name: GitVersionSetup
description: 'GitVersionSetup action'

runs:
  using: "composite"
  steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: "5.x"
    - name: GitVersion Show config
      uses: gittools/actions/gitversion/execute@v0
      with:
          useConfigFile: true
          configFilePath: ${{ github.action_path }}/../../GitVersion.yml
          additionalArguments: /showConfig
    - name: Determine GitVersion
      id: gitversion # id to later be referenced
      uses: gittools/actions/gitversion/execute@v0
      with:
          useConfigFile: true
          configFilePath: ${{ github.action_path }}/../../GitVersion.yml
          additionalArguments: /updateprojectfiles
