###
## This workflow is made specifically for .net 7 with workaround for multi platform build
###
name: docker_ci_build_publish
on: 
    workflow_call:
        inputs:
            registry_host:
              required: false
              type: string
            registry_username:
              required: false
              type: string
            build_platforms:
              required: true
              type: string
            always_push_docker:
              required: false
              type: boolean
            docker_context:
              required: false
              type: string
              default: .
            docker_file:
              required: false
              type: string
            image-description:
              description: Image description which will be shown in github container registry
              required: false
              type: string
              default: ''
        secrets:
            token:
              required: true
        outputs:
            sem_ver:
              description: "SemVer from GitVersion"
              value: ${{ jobs.build.outputs.semVer }}
            docker_image_url:
              description: "Full docker repo url"
              value: ${{ jobs.build.outputs.imageUrl }}
          
env:
    IMAGE_NAME: ${{ github.event.repository.name }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        packages: write
        # This is used to complete the identity challenge
        # with sigstore/fulcio when running outside of PRs.
        id-token: write
    outputs:
      semVer: ${{ steps.gitversion_output.outputs.semVer }}
      imageUrl: ${{ steps.docker-image-url.outputs.imageUrl }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        if: ${{ env.ACT }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
      - name: Determine GitVersion
        id: gitversion
        uses: evoy-as/.github/.github/actions/gitversion-setup@main
      - name: Display Semver
        id: gitversion_output
        run: |
          echo "Semver: $GitVersion_SemVer"
          echo "semVer=$GitVersion_SemVer" >> $GITHUB_OUTPUT
      - uses: mukunku/tag-exists-action@v1.2.0
        id: checkTag
        with: 
          tag: 'v${{ steps.gitversion_output.outputs.semVer }}'
      - run: | 
          echo "Tag exists: ${{ steps.checkTag.outputs.exists }}"
      - name: Set pushDocker variable
        id: push-docker
        run: |
          echo "push_docker=${{ (github.event_name != 'pull_request' || inputs.always_push_docker == true) && steps.checkTag.outputs.exists == 'false' }}" >> "$GITHUB_OUTPUT"
      - name: Build and push Docker image
        id: docker-build
        #uses: evoy-as/.github/.github/actions/docker-buildx@main
        uses: evoy-as/.github/.github/actions/docker-buildx@main
        with:
          context: ${{ inputs.docker_context }}
          file: ${{ inputs.docker_file }}
          platforms: ${{ inputs.build_platforms }}
          push: ${{ steps.push-docker.outputs.push_docker}}
          registry: ${{ inputs.registry_host }}
          registry-username: ${{ inputs.registry_username }}
          registry-password: ${{ secrets.token }}
          repository: ${{ env.IMAGE_NAME }}
          tags: ${{ steps.gitversion_output.outputs.semVer }}
          #image-description: ${{ inputs.image-description }}
      - name: Output image url
        id: docker-image-url
        if: steps.push-docker.outputs.push_docker == 'true'
        run: | 
            metadata='${{ steps.docker-build.outputs.metadata }}'
            echo '$metadata'
            image_url=$(jq -r '."image.name"' <<< $metadata)
            echo "$image_url"
            echo "imageUrl=$image_url" >> "$GITHUB_OUTPUT"
      - name: Tag GitVersion
        if: success() && steps.checkTag.outputs.exists == 'false'
        id: gitversion-tag
        uses: evoy-as/.github/.github/actions/gitversion-tag@main
      