###
## This workflow is made specifically for .net 7 with workaround for multi platform build
###
name: docker_ci_build_publish
on: 
    workflow_call:
        inputs:
            build_platforms:
                required: true
                type: string
            always_push_docker:
              required: false
              type: boolean
        outputs:
            sem_ver:
              description: "SemVer from GitVersion"
              value: ${{ jobs.build.outputs.semVer }}
            docker_image_url:
              description: "Full docker repo url"
              value: ${{ jobs.build.outputs.imageUrl }}
          
env:
    REGISTRY: acrevoy.azurecr.io
    IMAGE_NAME: ${{ github.event.repository.name }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        packages: write
        # This is used to complete the identity challenge
        # with sigstore/fulcio when running outside of PRs.
        id-token: write
    outputs:
      semVer: ${{ steps.gitversion_output.outputs.semVer }}
      imageUrl: ${{ steps.docker-image-url.outputs.imageUrl }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Determine GitVersion
        id: gitversion
        uses: evoy-as/.github/.github/actions/gitversion-setup@main
      - name: Display Semver
        id: gitversion_output
        run: |
          echo "Semver: $GitVersion_SemVer"
          echo "semVer=$GitVersion_SemVer" >> $GITHUB_OUTPUT
      # Support multi-platform
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
      - uses: mukunku/tag-exists-action@v1.2.0
        id: checkTag
        with: 
          tag: 'v${{ steps.gitversion_output.outputs.semVer }}'
      - run: | 
          echo "Tag exists: ${{ steps.checkTag.outputs.exists }}"
      - id: push-docker
        run: |
          echo "always push to docker: ${{ inputs.always_push_docker }}"
          echo "pushDocker=${{ (github.event_name != 'pull_request' || inputs.always_push_docker == true) && steps.checkTag.outputs.exists == false }}" >> $env:GITHUB_OUTPUT
      - name: Log into registry ${{ env.REGISTRY }}
        if: steps.push-docker.outputs.pushDocker
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
            registry: ${{ env.REGISTRY }}
            username: ${{ vars.ACR_USER }}
            password: ${{ secrets.ACR_PASSWORD }}
      - id: docker-image-url
        if: (github.event_name != 'pull_request' || inputs.always_push_docker) && steps.checkTag.outputs.exists == false
        run: | 
            echo "imageUrl=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.gitversion_output.outputs.semVer }}" >> $env:GITHUB_OUTPUT
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
            context: .
            push: ${{ steps.push-docker.outputs.pushDocker == 'true' }}
            tags: | 
              ${{ steps.docker-image-url.outputs.imageUrl }}
            platforms: ${{ inputs.build_platforms }}
            cache-from: type=gha
            cache-to: type=gha,mode=max
      - name: Tag GitVersion
        if: success() && steps.checkTag.outputs.exists == false
        id: gitversion-tag
        uses: evoy-as/.github/.github/actions/gitversion-tag@main
      